[[re2c]]
arch = "aarch64"
git-tree-sha1 = "f280414dcc824bdc6041b28a77911edcc7eba53d"
os = "macos"

    [[re2c.download]]
    sha256 = "ee19802228c0420f2d8dc8c8d87cdf71e58f97f4b45a712acaf2923206a414b4"
    url = "https://github.com/JuliaBinaryWrappers/re2c_jll.jl/releases/download/re2c-v3.1.0+0/re2c.v3.1.0.aarch64-apple-darwin.tar.gz"
[[re2c]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "8244a1563b9fb01d2999ef4b92ad70901dd50159"
libc = "glibc"
os = "linux"

    [[re2c.download]]
    sha256 = "8dea14d62ac73b1a06d220174e1ad3413e42bc0cccb17212af6f36e9c0f6c8ee"
    url = "https://github.com/JuliaBinaryWrappers/re2c_jll.jl/releases/download/re2c-v3.1.0+0/re2c.v3.1.0.aarch64-linux-gnu-cxx03.tar.gz"
[[re2c]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "c6876b6e381af339b685329cc90df6b20a2ead84"
libc = "glibc"
os = "linux"

    [[re2c.download]]
    sha256 = "388440d9aba2809c92d7adb62141efc2618fac4ff38c26b6d8660fdf95be8910"
    url = "https://github.com/JuliaBinaryWrappers/re2c_jll.jl/releases/download/re2c-v3.1.0+0/re2c.v3.1.0.aarch64-linux-gnu-cxx11.tar.gz"
[[re2c]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "3b8c415349fd3c3ac53490ab15ce6745fa64e4e1"
libc = "musl"
os = "linux"

    [[re2c.download]]
    sha256 = "af8e1f598c05ade9ca139d4ad03a73e908f271ec765419c5892fb5231f5627fb"
    url = "https://github.com/JuliaBinaryWrappers/re2c_jll.jl/releases/download/re2c-v3.1.0+0/re2c.v3.1.0.aarch64-linux-musl-cxx03.tar.gz"
[[re2c]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "a8e7315475b2fc829043a9239f86ae8ab0742aab"
libc = "musl"
os = "linux"

    [[re2c.download]]
    sha256 = "ad0a298749d8b51102c645da935891694fbfe4aec598129dcb2f822e8d98e051"
    url = "https://github.com/JuliaBinaryWrappers/re2c_jll.jl/releases/download/re2c-v3.1.0+0/re2c.v3.1.0.aarch64-linux-musl-cxx11.tar.gz"
[[re2c]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "1bfffa7176d42ba466fb786d213ed81704488885"
libc = "glibc"
os = "linux"

    [[re2c.download]]
    sha256 = "4ce1e17638b7a25a965ccccb8fcc913fe16515b7130db69b11363f26cbeafe0b"
    url = "https://github.com/JuliaBinaryWrappers/re2c_jll.jl/releases/download/re2c-v3.1.0+0/re2c.v3.1.0.armv6l-linux-gnueabihf-cxx03.tar.gz"
[[re2c]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "9bd84ac70d124c78e9cf5179ab90994cbe236b82"
libc = "glibc"
os = "linux"

    [[re2c.download]]
    sha256 = "345eb0ed2136a484b70749fdfc14c79588e7382c354010720baec65cb1be315f"
    url = "https://github.com/JuliaBinaryWrappers/re2c_jll.jl/releases/download/re2c-v3.1.0+0/re2c.v3.1.0.armv6l-linux-gnueabihf-cxx11.tar.gz"
[[re2c]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "1dde4dc9283d91771c37cfff5675b0656eb4d56c"
libc = "musl"
os = "linux"

    [[re2c.download]]
    sha256 = "a926a63b76589221fc300d823d984d33df6c10eb27d5ceaf058bc7600b30c2dd"
    url = "https://github.com/JuliaBinaryWrappers/re2c_jll.jl/releases/download/re2c-v3.1.0+0/re2c.v3.1.0.armv6l-linux-musleabihf-cxx03.tar.gz"
[[re2c]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "242ca884447d7bbb77f6503c5a0f5d4f054cbf30"
libc = "musl"
os = "linux"

    [[re2c.download]]
    sha256 = "bf41b5066d4d1501c9902e8e9797a01760c8e492c91c71baf436b390e6b81ca1"
    url = "https://github.com/JuliaBinaryWrappers/re2c_jll.jl/releases/download/re2c-v3.1.0+0/re2c.v3.1.0.armv6l-linux-musleabihf-cxx11.tar.gz"
[[re2c]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "bfb1c89d2c854a13e33897688b3709d46d7417e7"
libc = "glibc"
os = "linux"

    [[re2c.download]]
    sha256 = "94256fd7c87e44f316fac7b8e9c07d76cc9cc744e62676824396b662ef1e3b41"
    url = "https://github.com/JuliaBinaryWrappers/re2c_jll.jl/releases/download/re2c-v3.1.0+0/re2c.v3.1.0.armv7l-linux-gnueabihf-cxx03.tar.gz"
[[re2c]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "9fd6f556be6a3b947a9ecef2a494accbd40b125c"
libc = "glibc"
os = "linux"

    [[re2c.download]]
    sha256 = "ab6fb70fa0ab4bc3f1ba61d4f8f444a5dd5950bee0a20158b97eaff46c7b810b"
    url = "https://github.com/JuliaBinaryWrappers/re2c_jll.jl/releases/download/re2c-v3.1.0+0/re2c.v3.1.0.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[re2c]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "c677e1d30b4674421fc02550a0f7d884433563ab"
libc = "musl"
os = "linux"

    [[re2c.download]]
    sha256 = "ad454d63a5fe5d231b4885445e1aff4578a02781f7945c919214e6f767227588"
    url = "https://github.com/JuliaBinaryWrappers/re2c_jll.jl/releases/download/re2c-v3.1.0+0/re2c.v3.1.0.armv7l-linux-musleabihf-cxx03.tar.gz"
[[re2c]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "e80e187a63bbd7a6d09004652f3082a6fef4fbf8"
libc = "musl"
os = "linux"

    [[re2c.download]]
    sha256 = "ec0193ee1a91fa9304e165dba0e88c07df5c2d73eed5a128394ee78e0a6eb78e"
    url = "https://github.com/JuliaBinaryWrappers/re2c_jll.jl/releases/download/re2c-v3.1.0+0/re2c.v3.1.0.armv7l-linux-musleabihf-cxx11.tar.gz"
[[re2c]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "3b06dafdcdf7085f4153a5a5137e3dcbae9c5012"
libc = "glibc"
os = "linux"

    [[re2c.download]]
    sha256 = "5f666e33dd527a30c8bbb68e64965fe27ae0d3c4fc7c458b337ea35afe0282ab"
    url = "https://github.com/JuliaBinaryWrappers/re2c_jll.jl/releases/download/re2c-v3.1.0+0/re2c.v3.1.0.i686-linux-gnu-cxx03.tar.gz"
[[re2c]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "350013505aa173b276e3f276f5bcf1a47f491ecc"
libc = "glibc"
os = "linux"

    [[re2c.download]]
    sha256 = "12d1160054056735ad760f8ed9612c532f117c3fa6307985cbed786ae7cf3dc9"
    url = "https://github.com/JuliaBinaryWrappers/re2c_jll.jl/releases/download/re2c-v3.1.0+0/re2c.v3.1.0.i686-linux-gnu-cxx11.tar.gz"
[[re2c]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "af62641851882b5acbe657e4798e936efa049ca6"
libc = "musl"
os = "linux"

    [[re2c.download]]
    sha256 = "fae205fd4db9eb1870d0a7ac9b0bf0fabef69192afd4e1a1b6b5a4a6146b3ae1"
    url = "https://github.com/JuliaBinaryWrappers/re2c_jll.jl/releases/download/re2c-v3.1.0+0/re2c.v3.1.0.i686-linux-musl-cxx03.tar.gz"
[[re2c]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "eeb97d6754b35bb0723d40388b56532aff4acb8d"
libc = "musl"
os = "linux"

    [[re2c.download]]
    sha256 = "97607fb47389b7736a7979db17388387ede6c611732cd98df96a8beade177b99"
    url = "https://github.com/JuliaBinaryWrappers/re2c_jll.jl/releases/download/re2c-v3.1.0+0/re2c.v3.1.0.i686-linux-musl-cxx11.tar.gz"
[[re2c]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "c885edcbffd0d0c14d8821a782f1319140fbada6"
os = "windows"

    [[re2c.download]]
    sha256 = "baa94154aa89bc9e570369c79a7870f73d98829bc1af1ab358e30fa6f71b9fb3"
    url = "https://github.com/JuliaBinaryWrappers/re2c_jll.jl/releases/download/re2c-v3.1.0+0/re2c.v3.1.0.i686-w64-mingw32-cxx03.tar.gz"
[[re2c]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "0714237acc47f9073d0dfbb13eba0ee5731ae1fa"
os = "windows"

    [[re2c.download]]
    sha256 = "90b047b0185ded7231787f3832ba480c2551acec59ed7a2b65e2cd90bf66b16d"
    url = "https://github.com/JuliaBinaryWrappers/re2c_jll.jl/releases/download/re2c-v3.1.0+0/re2c.v3.1.0.i686-w64-mingw32-cxx11.tar.gz"
[[re2c]]
arch = "powerpc64le"
cxxstring_abi = "cxx03"
git-tree-sha1 = "751e87607e43b771e08f88a66a4a79ae5d3358d3"
libc = "glibc"
os = "linux"

    [[re2c.download]]
    sha256 = "c8c21152dabcb603331f106b3351844fcc6a152bb97856e4bc171cdbe2351061"
    url = "https://github.com/JuliaBinaryWrappers/re2c_jll.jl/releases/download/re2c-v3.1.0+0/re2c.v3.1.0.powerpc64le-linux-gnu-cxx03.tar.gz"
[[re2c]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "ffd5dcabfad051a7fd12930eb95cf0b8dd4d966f"
libc = "glibc"
os = "linux"

    [[re2c.download]]
    sha256 = "8557d978e65161955b1dc0e22d6c5639d38549b69ed06df6ec480887efcedfb0"
    url = "https://github.com/JuliaBinaryWrappers/re2c_jll.jl/releases/download/re2c-v3.1.0+0/re2c.v3.1.0.powerpc64le-linux-gnu-cxx11.tar.gz"
[[re2c]]
arch = "x86_64"
git-tree-sha1 = "78a5ddf45324bc49fd068937580c61243c7c0530"
os = "macos"

    [[re2c.download]]
    sha256 = "7af36e043de298b61c752eda927e3de46e795c0d62142ec938768dcf68f47a5d"
    url = "https://github.com/JuliaBinaryWrappers/re2c_jll.jl/releases/download/re2c-v3.1.0+0/re2c.v3.1.0.x86_64-apple-darwin.tar.gz"
[[re2c]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "fbd2b3ad38ce2f0c3d22d3036b295b161c5d4238"
libc = "glibc"
os = "linux"

    [[re2c.download]]
    sha256 = "4881054a674cce9bdcc1114a68d3a7b176b3de41dc9f971050ffdba2f517185d"
    url = "https://github.com/JuliaBinaryWrappers/re2c_jll.jl/releases/download/re2c-v3.1.0+0/re2c.v3.1.0.x86_64-linux-gnu-cxx03.tar.gz"
[[re2c]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "cbedf8374c27c0b35b40685c9c98624e22a0217b"
libc = "glibc"
os = "linux"

    [[re2c.download]]
    sha256 = "d2b32ed52822880b971e031cdd484ec01f193332d03625666866fad82f0530b2"
    url = "https://github.com/JuliaBinaryWrappers/re2c_jll.jl/releases/download/re2c-v3.1.0+0/re2c.v3.1.0.x86_64-linux-gnu-cxx11.tar.gz"
[[re2c]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "8e1104199a015bcadf97c8e6720c3b4687f15702"
libc = "musl"
os = "linux"

    [[re2c.download]]
    sha256 = "3c53eace3cd3173b1cc7096fd0cc78850d399f71a614da732411f86971221a83"
    url = "https://github.com/JuliaBinaryWrappers/re2c_jll.jl/releases/download/re2c-v3.1.0+0/re2c.v3.1.0.x86_64-linux-musl-cxx03.tar.gz"
[[re2c]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "4a18818582560c18d355a51847b571466575a089"
libc = "musl"
os = "linux"

    [[re2c.download]]
    sha256 = "d5d6bbd3625b748458907954d6e1c30ed69c339f12c6c761c56884871fda6a7d"
    url = "https://github.com/JuliaBinaryWrappers/re2c_jll.jl/releases/download/re2c-v3.1.0+0/re2c.v3.1.0.x86_64-linux-musl-cxx11.tar.gz"
[[re2c]]
arch = "x86_64"
git-tree-sha1 = "722ec81426759872c8150cf4bce0b728198a4839"
os = "freebsd"

    [[re2c.download]]
    sha256 = "01a77c3158da13a384eb7c1206a4330d6d32249493ce5213b97788adeb24c67b"
    url = "https://github.com/JuliaBinaryWrappers/re2c_jll.jl/releases/download/re2c-v3.1.0+0/re2c.v3.1.0.x86_64-unknown-freebsd.tar.gz"
[[re2c]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "8bd71b9c080529a16e318b520056a0eb372b2467"
os = "windows"

    [[re2c.download]]
    sha256 = "709a432d89a17760cd4be652105ddeab2245dbfa78d12223ee89a7e0b72cc7ad"
    url = "https://github.com/JuliaBinaryWrappers/re2c_jll.jl/releases/download/re2c-v3.1.0+0/re2c.v3.1.0.x86_64-w64-mingw32-cxx03.tar.gz"
[[re2c]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "7cc6b99c5cb684192b9ee9aed829683114b5cd69"
os = "windows"

    [[re2c.download]]
    sha256 = "b29e6ba870bf1fa7e1677e374478fde07ab674dcf460446f1481eb09871c01bd"
    url = "https://github.com/JuliaBinaryWrappers/re2c_jll.jl/releases/download/re2c-v3.1.0+0/re2c.v3.1.0.x86_64-w64-mingw32-cxx11.tar.gz"
